### ISSUE TITLE
Genes Not Being Extracted (empty .fna files)

### ISSUE THREAD

**Issue by gakindler** [motu-tool/fetchMGs.pl#1]
Hello,

I've been running;

`./fetchMGs.pl -m extraction protein.faa -d contigs.fasta -o fetchMGs`

and my output file contains the extracted proteins (.faa) files but the gene (.fna) files are empty. My contigs.fasta file was assembled using SPAdes and my protein.faa was predicted using Prodigal. Any ideas on why this might be happening, please?

Cheers,

G

**Comment by hjruscheweyh** [comment]
Hi!
Thanks for using fetchMGs.

My hunch is that the names in the sequences in the protein.faa do not match the names in the contigs.fna file. That would be strange because prodigal doesnt mess up names...

You can check in your outputfolder `fetchMGs/temp/*IDs.txt`. That are the names that seqtk will try to extract from both files (protein.faa and contigs.fna). If no sequence can be extracted using that names then this will lead to empty files.



Best,
Hans

**Comment by gakindler** [comment]
Thank you for making the tool! We really appreciate your work.

Using a COG*.IDs.txt file, I took the contig names and searched the protein.faa file. Every COG ID was accounted for. I then took the same contig names and searched the contigs.fasta file and got nothing.

Looking manually I found the following difference:

Protein file: 

> NODE_103_length_48414_cov_6.693852

Gene files: 

> NODE_103_length_48414_cov_6.693852_29

The addition of the _29 was consistent with the other contig names. They all had an added suffix of _*.

Looks like your hunch is correct!

**Comment by hjruscheweyh** [comment]
Great!

I will close this issue as the problem has been solved. Let me know if there is anything else.

Hans

**Comment by gakindler** [comment]
Thank you Hans.

Just one thing, how can I get around this so I can use FetchMGs to extract from the gene files? As that is what I am after.

**Comment by pangenomics** [comment]
Hi,
Having another look at this it seems that you are using the protein files and the contig files. Please try using the protein files and the nucleotide sequences of the genes. 

Best wishes,
Daniel

**Comment by gakindler** [comment]
Thank you Daniel!
